name = "SingularityAppBuilder"
uuid = "07df0c89-a9b5-4942-b174-e2c9ade988fa"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
